mkdir -p ./obj
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/metaset.o metaset.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/metacheck.o metacheck.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/globalinit.o globalinit.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/argvcopy.o argvcopy.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/compat.o compat.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/metaget.o metaget.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/stackinit.o stackinit.c
clang -I. -I../metapagetable -target riscv64-unknown-linux-gnu -c -Werror -Wall -flto -fPIC -std=gnu++11 -mriscv=RV64IMAFD -nostdinc  -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/lib/gcc/riscv64-unknown-linux-gnu/5.3.0/include-fixed -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/riscv64-unknown-linux-gnu/include -isystem /home/jsshin/projects/riscv/all_tools_linux/riscv/sysroot/usr/include -O3 -MMD -o obj/metastack.o metastack.cc
llvm-ar crv obj/libmetadata.a ./obj/metaset.o ./obj/metacheck.o ./obj/globalinit.o ./obj/argvcopy.o ./obj/compat.o ./obj/metaget.o ./obj/stackinit.o ./obj/metastack.o
llvm-ranlib obj/libmetadata.a
cp obj/*.o /home/jwseo/workspace/MTE/midfat/autosetup.dir/framework/obj/staticlib-dummy
ls -al /home/jwseo/workspace/MTE/midfat/autosetup.dir/framework/obj/staticlib-dummy/libmetadata.a
